jest.mock('../../services/roleService',()=>({createRole:jest.fn(),getAllRoles:jest.fn(),getRoleById:jest.fn(),updateRole:jest.fn(),deleteRole:jest.fn()}));
const svc=require('../../services/roleService'),c=require('../../controllers/roleController'); const res=()=>{const r={status:jest.fn(),json:jest.fn()};r.status.mockReturnValue(r);return r;};
describe('roleController',()=>{beforeEach(()=>jest.clearAllMocks());
 test('create success/error',async()=>{svc.createRole.mockResolvedValue({});let r=res();await c.createRoleHandler({body:{}},r);expect(r.status).toHaveBeenCalledWith(201);svc.createRole.mockRejectedValue(new Error('bad'));r=res();await c.createRoleHandler({body:{}},r);expect(r.status).toHaveBeenCalledWith(400);});
 test('list success/error',async()=>{svc.getAllRoles.mockResolvedValue([]);let r=res();await c.listRoles({},r);expect(r.status).toHaveBeenCalledWith(200);svc.getAllRoles.mockRejectedValue(new Error('bad'));r=res();await c.listRoles({},r);expect(r.status).toHaveBeenCalledWith(500);});
 test('get role success/not found/error',async()=>{svc.getRoleById.mockResolvedValue({});let r=res();await c.getRole({params:{id:'1'}},r);expect(r.status).toHaveBeenCalledWith(200);svc.getRoleById.mockResolvedValue(null);r=res();await c.getRole({params:{id:'1'}},r);expect(r.status).toHaveBeenCalledWith(404);svc.getRoleById.mockRejectedValue(new Error('bad'));r=res();await c.getRole({params:{id:'1'}},r);expect(r.status).toHaveBeenCalledWith(500);});
 test('update success/not found/error',async()=>{svc.updateRole.mockResolvedValue({});let r=res();await c.updateRoleHandler({params:{id:'1'},body:{}},r);expect(r.status).toHaveBeenCalledWith(200);svc.updateRole.mockResolvedValue(null);r=res();await c.updateRoleHandler({params:{id:'1'},body:{}},r);expect(r.status).toHaveBeenCalledWith(404);svc.updateRole.mockRejectedValue(new Error('bad'));r=res();await c.updateRoleHandler({params:{id:'1'},body:{}},r);expect(r.status).toHaveBeenCalledWith(400);});
 test('delete success/error',async()=>{svc.deleteRole.mockResolvedValue(true);let r=res();await c.deleteRoleHandler({params:{id:'1'}},r);expect(r.status).toHaveBeenCalledWith(200);svc.deleteRole.mockRejectedValue(new Error('bad'));r=res();await c.deleteRoleHandler({params:{id:'1'}},r);expect(r.status).toHaveBeenCalledWith(400);});
});
